version: "3.9"
services:
  database:
    image: mongo
    hostname: localhost
    container_name: dbAppDemo
    environment:
      MONGO_INITDB_DATABASE: appcrud
    volumes:
      - ./database:/data/db
    restart: always
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: AppDemo
    environment:
      DB_URL: mongodb://database:27017/
    ports:
      - 8000:8080
    depends_on:
      - database
    volumes:
      - .:/appDemo
    restart: always
